Repository pandeyaman2170/HAD_Project_backend, pull requests merged in 2024-04, with the labels that each got.

#39 UtilityApi-for-video-call
  src/main/java/com/example/teleconsultationbackend/Controller/DepartmentController.java
  src/main/java/com/example/teleconsultationbackend/Controller/DoctorController.java
  src/main/java/com/example/teleconsultationbackend/Controller/PatientController.java
  src/main/java/com/example/teleconsultationbackend/Controller/QueuesController.java
  src/main/java/com/example/teleconsultationbackend/DTO/DoctorDetails.java
  src/main/java/com/example/teleconsultationbackend/Repository/DoctorRepository.java
  src/main/java/com/example/teleconsultationbackend/Service/DepartmentService.java
  src/main/java/com/example/teleconsultationbackend/Service/DepartmentServiceImplementation.java
  src/main/java/com/example/teleconsultationbackend/Service/DoctorService.java
  src/main/java/com/example/teleconsultationbackend/Service/DoctorServiceImplementation.java
  src/main/java/com/example/teleconsultationbackend/Service/PatientServiceImpl.java
  src/main/java/com/example/teleconsultationbackend/Service/QueueService.java
  src/main/java/com/example/teleconsultationbackend/Service/QueueServiceImpl.java
Labels: feature

#40 accpet-call-reject
  src/main/java/com/example/teleconsultationbackend/Controller/QueuesController.java
  src/main/java/com/example/teleconsultationbackend/Service/QueueService.java
  src/main/java/com/example/teleconsultationbackend/Service/QueueServiceImpl.java
Labels: feature

#41 web-socket-Configration-and-api
  src/main/java/com/example/teleconsultationbackend/Config/SecurityConfiguration.java
  src/main/java/com/example/teleconsultationbackend/Config/WebMvcConfig.java
  src/main/java/com/example/teleconsultationbackend/Config/WebSocketConfig.java
  src/main/java/com/example/teleconsultationbackend/Controller/Consultation1Controller.java
  src/main/java/com/example/teleconsultationbackend/Controller/PatientController.java
  src/main/java/com/example/teleconsultationbackend/Entity/Consultation1.java
  src/main/java/com/example/teleconsultationbackend/Repository/Consultation1Repository.java
  src/main/java/com/example/teleconsultationbackend/Service/Consultation1Service.java
  src/main/java/com/example/teleconsultationbackend/Service/Consultation1ServiceImplementation.java
  src/main/java/com/example/teleconsultationbackend/Service/PatientServiceImpl.java
  src/main/java/com/example/teleconsultationbackend/TeleConsultationBackendApplication.java
Labels: bug

#43 medical-history-api
  pom.xml
  src/main/java/com/example/teleconsultationbackend/Controller/Consultation1Controller.java
  src/main/java/com/example/teleconsultationbackend/Controller/PrescriptionController.java
  src/main/java/com/example/teleconsultationbackend/Repository/Consultation1Repository.java
  src/main/java/com/example/teleconsultationbackend/Service/PatientServiceImpl.java
  src/main/java/com/example/teleconsultationbackend/Service/PrescriptionServiceImplementation.java
Labels: bug

#44 Adding Entity Constraint
  src/main/java/com/example/teleconsultationbackend/Entity/Department.java
  src/main/java/com/example/teleconsultationbackend/Entity/Doctor.java
  src/main/java/com/example/teleconsultationbackend/Entity/GlobalAdmin.java
  src/main/java/com/example/teleconsultationbackend/Entity/Hospital.java
  src/main/java/com/example/teleconsultationbackend/Entity/Patient.java
  src/main/java/com/example/teleconsultationbackend/Entity/User.java
Labels: bug

#45 adding swagger Information in controllers.
  src/main/java/com/example/teleconsultationbackend/Controller/ConsultationController.java
  src/main/java/com/example/teleconsultationbackend/Controller/DepartmentController.java
  src/main/java/com/example/teleconsultationbackend/Controller/DoctorController.java
  src/main/java/com/example/teleconsultationbackend/Controller/GlobalAdminController.java
  src/main/java/com/example/teleconsultationbackend/Controller/HomeController.java
  src/main/java/com/example/teleconsultationbackend/Controller/HomePageController.java
  src/main/java/com/example/teleconsultationbackend/Controller/HospitalController.java
  src/main/java/com/example/teleconsultationbackend/Controller/PatientController.java
  src/main/java/com/example/teleconsultationbackend/Controller/PdfController.java
  src/main/java/com/example/teleconsultationbackend/Controller/PrescriptionController.java
  src/main/java/com/example/teleconsultationbackend/Controller/QueuesController.java
  src/main/java/com/example/teleconsultationbackend/Controller/ShareRecordController.java
  src/main/java/com/example/teleconsultationbackend/Controller/UserController.java
  src/main/java/com/example/teleconsultationbackend/DTO/OnlyPatientDetails.java
Labels: enhancement

#49 adding-consultation1-to-consultation
  src/main/java/com/example/teleconsultationbackend/Controller/Consultation1Controller.java
  src/main/java/com/example/teleconsultationbackend/Controller/ConsultationController.java
  src/main/java/com/example/teleconsultationbackend/Entity/Consultation.java
  src/main/java/com/example/teleconsultationbackend/Entity/Consultation1.java
  src/main/java/com/example/teleconsultationbackend/Entity/Doctor.java
  src/main/java/com/example/teleconsultationbackend/Repository/Consultation1Repository.java
  src/main/java/com/example/teleconsultationbackend/Service/Consultation1Service.java
  src/main/java/com/example/teleconsultationbackend/Service/Consultation1ServiceImplementation.java
  src/main/java/com/example/teleconsultationbackend/Service/ConsultationService.java
  src/main/java/com/example/teleconsultationbackend/Service/ConsultationServiceImplemetation.java
  src/main/java/com/example/teleconsultationbackend/Service/PatientServiceImpl.java
  src/main/java/com/example/teleconsultationbackend/Service/PrescriptionServiceImplementation.java
Labels: bug

#54 consultation-controller-table-update
  src/main/java/com/example/teleconsultationbackend/Controller/ConsultationController.java
  src/main/java/com/example/teleconsultationbackend/Repository/ConsultationRepository.java
  src/main/java/com/example/teleconsultationbackend/Service/ConsultationServiceImplemetation.java
  src/main/java/com/example/teleconsultationbackend/Service/PrescriptionServiceImplementation.java
  src/main/java/com/example/teleconsultationbackend/Service/QueueServiceImpl.java
Labels: bug

#56 sharing-records-between-hospitals
  src/main/java/com/example/teleconsultationbackend/Controller/ShareRecordController.java
  src/main/java/com/example/teleconsultationbackend/Entity/ShareRecordHospital.java
  src/main/java/com/example/teleconsultationbackend/Repository/ShareRecordRepository.java
  src/main/java/com/example/teleconsultationbackend/Service/ShareRecordImplementation.java
  src/main/java/com/example/teleconsultationbackend/Service/ShareRecordService.java
Labels: feature

#57 refresh-button
  src/main/java/com/example/teleconsultationbackend/Controller/PrescriptionController.java
  src/main/java/com/example/teleconsultationbackend/Repository/ConsultationRepository.java
  src/main/java/com/example/teleconsultationbackend/Service/ConsultationService.java
  src/main/java/com/example/teleconsultationbackend/Service/PrescriptionServiceImplementation.java
  src/main/java/com/example/teleconsultationbackend/Service/QueueServiceImpl.java
Labels: bug

#59 queue-NPE-fixed
  src/main/java/com/example/teleconsultationbackend/Controller/ConsultationController.java
  src/main/java/com/example/teleconsultationbackend/Controller/PatientController.java
  src/main/java/com/example/teleconsultationbackend/Service/ConsultationService.java
  src/main/java/com/example/teleconsultationbackend/Service/ConsultationServiceImplemetation.java
  src/main/java/com/example/teleconsultationbackend/Service/PatientServiceImpl.java
  src/main/java/com/example/teleconsultationbackend/Service/QueueServiceImpl.java
  target/classes/com/example/teleconsultationbackend/Repository/PatientRepository.class
Labels: bug

#62 Followup implemented at patient side.
  src/main/java/com/example/teleconsultationbackend/Controller/ConsultationController.java
  src/main/java/com/example/teleconsultationbackend/Controller/PatientController.java
  src/main/java/com/example/teleconsultationbackend/DTO/FollowUpDetails.java
  src/main/java/com/example/teleconsultationbackend/Service/PrescriptionService.java
  src/main/java/com/example/teleconsultationbackend/Service/PrescriptionServiceImplementation.java
  src/main/java/com/example/teleconsultationbackend/Service/QueueServiceImpl.java
Labels: feature

#60 repeat-call UI fixed
  src/main/java/com/example/teleconsultationbackend/Controller/ConsultationController.java
  src/main/java/com/example/teleconsultationbackend/Controller/PatientController.java
Labels: bug

#61 made update un add doctor
  src/main/java/com/example/teleconsultationbackend/Controller/HospitalController.java
  src/main/java/com/example/teleconsultationbackend/Controller/UserController.java
  src/main/java/com/example/teleconsultationbackend/Service/DoctorServiceImplementation.java
  src/main/java/com/example/teleconsultationbackend/Service/GlobalAdminServiceImplementation.java
Labels: enhancement

#63 made change in doctor details
  src/main/java/com/example/teleconsultationbackend/DTO/DoctorDetails.java
Labels: enhancement
