Repository pandeyaman2170/HAD_Project_backend, pull requests merged in 2024-03, with the labels that each got.

#13 prescription-consulatation
  .idea/workspace.xml
  pom.xml
  src/main/java/com/example/teleconsultationbackend/Controller/ConsultationController.java
  src/main/java/com/example/teleconsultationbackend/Controller/GlobalAdminController.java
  src/main/java/com/example/teleconsultationbackend/Controller/PdfController.java
  src/main/java/com/example/teleconsultationbackend/Controller/PrescriptionController.java
  src/main/java/com/example/teleconsultationbackend/DTO/DateWiseConsultations.java
  src/main/java/com/example/teleconsultationbackend/DTO/MonthWiseConsultation.java
  src/main/java/com/example/teleconsultationbackend/DTO/PrescriptionDetails.java
  src/main/java/com/example/teleconsultationbackend/Entity/Consultation.java
  src/main/java/com/example/teleconsultationbackend/Entity/Prescription.java
  src/main/java/com/example/teleconsultationbackend/Images/logo.png
  src/main/java/com/example/teleconsultationbackend/Repository/ConsultationRepository.java
  src/main/java/com/example/teleconsultationbackend/Repository/PrescriptionRepository.java
  src/main/java/com/example/teleconsultationbackend/Service/ConsultationService.java
  src/main/java/com/example/teleconsultationbackend/Service/ConsultationServiceImplemetation.java
  src/main/java/com/example/teleconsultationbackend/Service/GlobalAdminService.java
  src/main/java/com/example/teleconsultationbackend/Service/GlobalAdminServiceImplementation.java
  src/main/java/com/example/teleconsultationbackend/Service/PdfService.java
  src/main/java/com/example/teleconsultationbackend/Service/PdfServiceImplementation.java
  src/main/java/com/example/teleconsultationbackend/Service/PrescriptionService.java
  src/main/java/com/example/teleconsultationbackend/Service/PrescriptionServiceImplementation.java
  src/main/resources/application.properties
  target/classes/application.properties
  target/classes/com/example/teleconsultationbackend/Controller/GlobalAdminController.class
  target/classes/com/example/teleconsultationbackend/Service/GlobalAdminService.class
  target/classes/com/example/teleconsultationbackend/Service/GlobalAdminServiceImplementation.class
Labels: enhancement

#14 add DTO for adding Doctor with hospital and department
  .idea/compiler.xml
  .idea/workspace.xml
  src/main/java/com/example/teleconsultationbackend/Controller/DepartmentController.java
  src/main/java/com/example/teleconsultationbackend/Controller/HospitalController.java
  src/main/java/com/example/teleconsultationbackend/DTO/DoctorDetails.java
  src/main/java/com/example/teleconsultationbackend/Entity/Doctor.java
  src/main/java/com/example/teleconsultationbackend/Entity/GlobalAdmin.java
  src/main/java/com/example/teleconsultationbackend/Entity/Hospital.java
  src/main/java/com/example/teleconsultationbackend/Repository/DepartmentRepository.java
  src/main/java/com/example/teleconsultationbackend/Repository/HospitalRepository.java
  src/main/java/com/example/teleconsultationbackend/Service/DepartmentService.java
  src/main/java/com/example/teleconsultationbackend/Service/DepartmentServiceImplementation.java
  src/main/java/com/example/teleconsultationbackend/Service/DoctorService.java
  src/main/java/com/example/teleconsultationbackend/Service/DoctorServiceImplementation.java
  src/main/java/com/example/teleconsultationbackend/Service/HospitalService.java
  src/main/java/com/example/teleconsultationbackend/Service/HospitalServiceImplementation.java
  target/classes/com/example/teleconsultationbackend/Controller/HospitalController.class
  target/classes/com/example/teleconsultationbackend/Entity/Doctor.class
  target/classes/com/example/teleconsultationbackend/Entity/GlobalAdmin.class
  target/classes/com/example/teleconsultationbackend/Entity/Hospital.class
  target/classes/com/example/teleconsultationbackend/Repository/DepartmentRepository.class
  target/classes/com/example/teleconsultationbackend/Repository/HospitalRepository.class
  target/classes/com/example/teleconsultationbackend/Service/HospitalService.class
  target/classes/com/example/teleconsultationbackend/Service/HospitalServiceImplementation.class
Labels: enhancement

#16 list-of-doctors-from-deparment
  .idea/workspace.xml
  src/main/java/com/example/teleconsultationbackend/Controller/QueuesController.java
  src/main/java/com/example/teleconsultationbackend/Entity/Department.java
  src/main/java/com/example/teleconsultationbackend/Entity/Doctor.java
  src/main/java/com/example/teleconsultationbackend/Entity/Patient.java
  src/main/java/com/example/teleconsultationbackend/Entity/Queues.java
  src/main/java/com/example/teleconsultationbackend/Entity/ShareRecordHospital.java
  src/main/java/com/example/teleconsultationbackend/Entity/User.java
  src/main/java/com/example/teleconsultationbackend/Service/HospitalServiceImplementation.java
  src/main/java/com/example/teleconsultationbackend/Service/QueueService.java
  src/main/java/com/example/teleconsultationbackend/Service/QueueServiceImpl.java
  src/main/resources/application.properties
  target/classes/application.properties
  target/classes/com/example/teleconsultationbackend/Entity/Department.class
  target/classes/com/example/teleconsultationbackend/Entity/Doctor.class
  target/classes/com/example/teleconsultationbackend/Entity/Patient.class
  target/classes/com/example/teleconsultationbackend/Entity/ShareRecordHospital.class
  target/classes/com/example/teleconsultationbackend/Entity/User.class
  target/classes/com/example/teleconsultationbackend/Service/HospitalServiceImplementation.class
Labels: enhancement

#17 JWT-patient
  .idea/workspace.xml
  pom.xml
  src/main/java/com/example/teleconsultationbackend/Config/JwtEntryPoint.java
  src/main/java/com/example/teleconsultationbackend/Config/SecurityConfiguration.java
  src/main/java/com/example/teleconsultationbackend/Controller/HomeController.java
  src/main/java/com/example/teleconsultationbackend/Controller/HospitalController.java
  src/main/java/com/example/teleconsultationbackend/Controller/PatientController.java
  src/main/java/com/example/teleconsultationbackend/Controller/PdfController.java
  src/main/java/com/example/teleconsultationbackend/Controller/PrescriptionController.java
  src/main/java/com/example/teleconsultationbackend/Controller/UserController.java
  src/main/java/com/example/teleconsultationbackend/DTO/PatientLoginStatus.java
  src/main/java/com/example/teleconsultationbackend/Entity/JwtRequest.java
  src/main/java/com/example/teleconsultationbackend/Entity/JwtResponse.java
  src/main/java/com/example/teleconsultationbackend/Filter/JwtFilter.java
  src/main/java/com/example/teleconsultationbackend/Repository/DoctorRepository.java
  src/main/java/com/example/teleconsultationbackend/Repository/PatientRepository.java
  src/main/java/com/example/teleconsultationbackend/Service/PatientService.java
  src/main/java/com/example/teleconsultationbackend/Service/PatientServiceImpl.java
  src/main/java/com/example/teleconsultationbackend/Service/PdfServiceImplementation.java
  src/main/java/com/example/teleconsultationbackend/Service/PrescriptionService.java
  src/main/java/com/example/teleconsultationbackend/Service/PrescriptionServiceImplementation.java
  src/main/java/com/example/teleconsultationbackend/Service/UserAuthenticationService.java
  src/main/java/com/example/teleconsultationbackend/Service/UserService.java
  src/main/java/com/example/teleconsultationbackend/Utility/JWTUtility.java
  src/main/resources/application.properties
  target/classes/application.properties
  target/classes/com/example/teleconsultationbackend/Controller/HospitalController.class
  target/classes/com/example/teleconsultationbackend/Controller/ShareRecordController.class
  target/classes/com/example/teleconsultationbackend/Repository/DoctorRepository.class
  target/classes/com/example/teleconsultationbackend/Repository/PatientRepository.class
Labels: enhancement

#18 fetch-doctor-by-phone-number
  .idea/workspace.xml
  src/main/java/com/example/teleconsultationbackend/Config/SecurityConfiguration.java
  src/main/java/com/example/teleconsultationbackend/Controller/AWSController.java
  src/main/java/com/example/teleconsultationbackend/Controller/ConsultationController.java
  src/main/java/com/example/teleconsultationbackend/Controller/DepartmentController.java
  src/main/java/com/example/teleconsultationbackend/Controller/DoctorController.java
  src/main/java/com/example/teleconsultationbackend/Controller/PatientController.java
  src/main/java/com/example/teleconsultationbackend/DTO/DoctorFetchDetails.java
  src/main/java/com/example/teleconsultationbackend/Service/DoctorService.java
  src/main/java/com/example/teleconsultationbackend/Service/DoctorServiceImplementation.java
  src/main/java/com/example/teleconsultationbackend/Service/PatientService.java
  src/main/java/com/example/teleconsultationbackend/Service/PatientServiceImpl.java
  src/main/resources/application.properties
  target/classes/application.properties
Labels: bug

#20 update-profile-api
  .idea/workspace.xml
  src/main/java/com/example/teleconsultationbackend/Controller/PatientController.java
  src/main/java/com/example/teleconsultationbackend/Service/PatientService.java
  src/main/java/com/example/teleconsultationbackend/Service/PatientServiceImpl.java
  src/main/resources/application.properties
  target/classes/application.properties
Labels: bug

#21 patient-updatiion-done
  .idea/workspace.xml
  src/main/java/com/example/teleconsultationbackend/Service/PatientServiceImpl.java
  src/main/resources/application.properties
  target/classes/application.properties
Labels: bug

#23 user-patient-login-status-validation
  .idea/workspace.xml
  src/main/java/com/example/teleconsultationbackend/Controller/DepartmentController.java
  src/main/java/com/example/teleconsultationbackend/Controller/UserController.java
  src/main/java/com/example/teleconsultationbackend/DTO/UserLoginStatus.java
  src/main/java/com/example/teleconsultationbackend/Repository/DoctorRepository.java
  src/main/java/com/example/teleconsultationbackend/Service/UserService.java
  target/classes/com/example/teleconsultationbackend/Repository/DoctorRepository.class
Labels: bug

#25 added global_admin login authhentication with JWT
  .gitignore
  src/main/java/com/example/teleconsultationbackend/Controller/GlobalAdminController.java
  src/main/java/com/example/teleconsultationbackend/Service/GlobalAdminService.java
  src/main/java/com/example/teleconsultationbackend/Service/GlobalAdminServiceImplementation.java
  target/classes/com/example/teleconsultationbackend/Controller/GlobalAdminController.class
  target/classes/com/example/teleconsultationbackend/Service/GlobalAdminService.class
  target/classes/com/example/teleconsultationbackend/Service/GlobalAdminServiceImplementation.class
Labels: feature

#27 reimplemented-add-department
  src/main/java/com/example/teleconsultationbackend/Controller/HospitalController.java
  src/main/java/com/example/teleconsultationbackend/Service/HospitalService.java
  src/main/java/com/example/teleconsultationbackend/Service/HospitalServiceImplementation.java
Labels: bug

#28 Total Patient are fetched in homepage
  src/main/java/com/example/teleconsultationbackend/Controller/HomePageController.java
  src/main/java/com/example/teleconsultationbackend/Repository/PatientRepository.java
  target/classes/com/example/teleconsultationbackend/Repository/DoctorRepository.class
  target/classes/com/example/teleconsultationbackend/Service/HospitalService.class
  target/classes/com/example/teleconsultationbackend/Service/HospitalServiceImplementation.class
Labels: bug

#32 added get_total_users
  src/main/java/com/example/teleconsultationbackend/Controller/UserController.java
  src/main/java/com/example/teleconsultationbackend/Repository/UserRepository.java
  src/main/java/com/example/teleconsultationbackend/Service/UserService.java
Labels: enhancement

#33 adding-utility-api
  src/main/java/com/example/teleconsultationbackend/Controller/DepartmentController.java
  src/main/java/com/example/teleconsultationbackend/Controller/PatientController.java
  src/main/java/com/example/teleconsultationbackend/Service/DepartmentService.java
  src/main/java/com/example/teleconsultationbackend/Service/DepartmentServiceImplementation.java
  src/main/java/com/example/teleconsultationbackend/Service/PatientServiceImpl.java
Labels: bug

#36 fetch-consultation-count-apis
  src/main/java/com/example/teleconsultationbackend/Config/SecurityConfiguration.java
  src/main/java/com/example/teleconsultationbackend/Controller/ConsultationController.java
  src/main/java/com/example/teleconsultationbackend/Repository/ConsultationRepository.java
  src/main/java/com/example/teleconsultationbackend/Service/ConsultationService.java
  src/main/java/com/example/teleconsultationbackend/Service/ConsultationServiceImplemetation.java
Labels: enhancement
