Repository pandeyaman2170/HAD_Project_backend, pull requests merged in 2024-05, with the labels that each got.

#64 created API for updating docotor detail by specific hospital
  src/main/java/com/example/teleconsultationbackend/Controller/ConsultationController.java
  src/main/java/com/example/teleconsultationbackend/Controller/GlobalAdminController.java
  src/main/java/com/example/teleconsultationbackend/Controller/HospitalController.java
  src/main/java/com/example/teleconsultationbackend/Service/DoctorService.java
  src/main/java/com/example/teleconsultationbackend/Service/DoctorServiceImplementation.java
Labels: enhancement, feature

#66 Doctor Deactivate Implemented
  src/main/java/com/example/teleconsultationbackend/Controller/HospitalController.java
  src/main/java/com/example/teleconsultationbackend/Entity/Doctor.java
  src/main/java/com/example/teleconsultationbackend/Service/DoctorService.java
  src/main/java/com/example/teleconsultationbackend/Service/DoctorServiceImplementation.java
  src/main/java/com/example/teleconsultationbackend/Service/UserService.java
Labels: feature

#65 handle-revoke-consent-patient
  src/main/java/com/example/teleconsultationbackend/Controller/ShareRecordController.java
  src/main/java/com/example/teleconsultationbackend/Service/ShareRecordImplementation.java
  src/main/java/com/example/teleconsultationbackend/Service/ShareRecordService.java
Labels: feature

#67 updated deactivate doctors in hospital admin
  src/main/java/com/example/teleconsultationbackend/DTO/DoctorFetchDetails.java
  src/main/java/com/example/teleconsultationbackend/Service/DoctorServiceImplementation.java
  src/main/java/com/example/teleconsultationbackend/Service/HospitalServiceImplementation.java
Labels: enhancement

#68 added-https-security-backend
  .gitignore
  src/main/resources/aman.jks
  src/main/resources/application.properties
Labels: feature
